name: SUSHI Publish to GitHub Pages

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 'current'
  
      - name: Install SUSHI
        run: npm install -g fsh-sushi
      
      - name: Install Publisher
        run: ./_updatePublisher.sh -y

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Ruby
        run: sudo apt install ruby ruby-all-dev -y

      - name: Install Jekyll
        run: sudo gem install jekyll jekyll-plantuml

      - name: Install Graphvix
        run: sudo apt install graphviz

      - name: Build IG
        run: ./_genonce.sh 

      - name: Publish IG Artefact
        uses: actions/upload-artifact@v3
        with:
          name: IG Archive
          path: ./output/

      - name: Prepare files for GitHub Pages
        run: |
          cp -r output _site;
          chmod -c -R +rX "_site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Publish IG to GitHub Pages
        uses: actions/upload-pages-artifact@v4

  # Deploy job (https://github.com/actions/deploy-pages)
  deploy:
    # Add a dependency to the build job
    needs: build
    # Only deploy on development branch
    # if: github.ref == 'refs/heads/development'
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action